name: Lint CloudFormation Templates
on: [push]
jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./*/*.yml
  cloudformation-Guard: 
    runs-on: ubuntu-latest
    steps:
      - name: Simple test
        uses: stelligent/cfn_nag@master
        with:
          input_path: 
            - ./aws-stack-cfn-demo3/aws-cfn-demo3.yml
            - ./aws-stack-cfn-demo2/aws-cfn-demo2.yml
            - ./aws-stack-cfn-demo1/aws-cfn-demo1.yml