name: Lint CloudFormation Templates
on: [push]
jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./aws-stack-demo1/aws-cfn-demo1.yml
          cfn-lint -t ./aws-stack-demo2/aws-cfn-demo2.yml
          cfn-lint -t ./aws-stack-demo3/aws-cfn-demo3.yml